name: barber_shop
description: Barber shop!

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  bloc: ^7.0.0
  flutter_bloc: ^7.0.0
  equatable: ^2.0.0
  get_it: ^7.1.3
  injectable: ^1.4.1
  get: ^4.1.4
  path_provider: ^2.0.2
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  flutter_svg: ^0.22.0
  flutter_screenutil: ^5.0.0+2
  hive_generator: ^1.1.0
  intl: ^0.17.0
  flutter_launcher_icons: ^0.9.1
  cupertino_icons: ^1.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
#  bloc_test: ^7.0.0
  injectable_generator: ^1.4.1
  build_runner: ^2.0.4
  hive_generator: ^1.1.0

flutter_icons:
#  android: "launcher_icon"
  ios: true
  android: true
  image_path: "assets/images/logo_light.png"


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    # assets-generator-begin
    # assets/images/*
    - assets/images/logo_light.png
    # assets/icons/*
    - assets/icons/circle_check.svg
    - assets/icons/close_icon.svg
    # assets-generator-end
  #   - images/a_dot_burr.jpeg
